basePath: /api/v1/
info:
  contact: {}
  description: 测试doc
  license: {}
  title: gin服务框架测试
  version: 0.0.1
paths:
  /record/{some_id}:
    get:
      consumes:
      - application/json
      description: 根据用户ID获取信息
      parameters:
      - description: 用户ID
        in: path
        name: some_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 测试中文注解
      tags:
      - Test
swagger: "2.0"
